CREATE DATABASE IF NOT EXISTS LIGA;
USE LIGA;

CREATE TABLE if not exists DATOSCLUB(
    ID INTEGER NOT NULL AUTO_INCREMENT, 
    PUNTOS INTEGER, 
    NOMBRE VARCHAR(50),
    MEDIA_GOLES DECIMAL(5,2) unsigned,
    FECHA DATE,
    PRIMARY KEY (ID)
    );

INSERT INTO DATOSCLUB VALUES(ID, 100, 'REAL MADRID CF', 2.35, '1902/03/06');   
INSERT INTO DATOSCLUB VALUES(ID, 94, 'REAL BETIS BALOMPIÉ', 1.90, '1907/09/12'); 
INSERT INTO DATOSCLUB VALUES(ID, 84, 'REAL SOCIEDAD DE FÚTBOL', 1.50, '1909/09/07'); 
INSERT INTO DATOSCLUB VALUES(ID, 80, 'VILLAREAL CLUB DE FÚTBOL', 1.25, '1923/03/10'); 